AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Linking the root domain to the sub domain account for orchestration stubs.
Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build

Mappings:
  EnvironmentConfiguration:
    dev:
      oidcHostedZoneId: Z092159727B0APSLCJ6S7
      authStubDomainName: authstub.oidc.authdev3.dev.account.gov.uk
      authStubResourceRecords:
        [
          ns-278.awsdns-34.com,
          ns-1784.awsdns-31.co.uk,
          ns-975.awsdns-57.net,
          ns-1086.awsdns-07.org,
        ]
    build:
      oidcHostedZoneId: Z062899930H8VN1UJ9CDX
      authStubDomainName: authstub.oidc.build.account.gov.uk
      authStubResourceRecords:
        [
          ns-120.awsdns-15.com,
          ns-575.awsdns-07.net,
          ns-1961.awsdns-53.co.uk,
          ns-1311.awsdns-35.org,
        ]

Resources:
  AuthStubNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: NS
      Name:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          authStubDomainName,
        ]
      HostedZoneId:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          oidcHostedZoneId,
        ]
      ResourceRecords:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          authStubResourceRecords,
        ]
      TTL: 172800
