version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
