AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Account intervention stub owned by Orchestration team

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    AllowedValues:
      - dev
      - build
  CodeSigningConfigArn:
    Type: String
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: none
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Default: none
  VpcStackName:
    Type: String
    Description: The name of the stack used to create the VPC

Conditions:
  UseCodeSigning: !Not [!Equals [none, !Ref CodeSigningConfigArn]]
  UsePermissionsBoundary: !Not [!Equals [none, !Ref PermissionsBoundary]]
  IsNotProduction: !Not [!Equals [!Ref Environment, production]]
  IsLocalEnv: !Equals [!Ref Environment, local]
  IsDev: !Equals [!Ref Environment, dev]

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Mappings:
  EnvironmentConfiguration:
    dev:
      oidcStubDomainName: oidc-stub.oidc.dev.account.gov.uk
      oidcStubIssuer: https://oidc-stub.oidc.dev.account.gov.uk
    build:
      oidcStubDomainName: oidc-stub.oidc.build.account.gov.uk
      oidcStubIssuer: https://oidc-stub.oidc.build.account.gov.uk

Resources:
  StubInterventionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-AIS-stub-interventions
      KeySchema:
        - AttributeName: pairwiseId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: pairwiseId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: stub-interventions

  AccountInterventionsStubApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Environment}-orch-ais-stub-api"
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - Fn::ImportValue: !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Action: "execute-api:Invoke"
              Principal: "*"
              Resource: "execute-api:/*"
            - Effect: Deny
              Action: "execute-api:Invoke"
              Principal: "*"
              Resource:
                - "execute-api:/*"
              Condition:
                StringNotEquals:
                  aws:SourceVpce:
                    - Fn::ImportValue: !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"
      MethodSettings:
        - CachingEnabled: false
          DataTraceEnabled: false
          HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: "OFF"
          MetricsEnabled: true
      TracingEnabled: true
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: !Sub "${Environment}-orch-ais-stub-api"
        paths:
          /v1/ais/{internalPairwiseId}:
            get:
              parameters:
                - name: internalPairwiseId
                  in: path
                  required: true
                  schema:
                    type: string
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AisStubInterventionsHandler.Arn}/invocations"
                requestParameters:
                  integration.request.path.internalPairwiseId: method.request.path.internalPairwiseId
                timeoutInMillis: 29000

  AisStubInterventionsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/ais-stub/ais-stub.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          # These will always be over-written when running locally in parameters.json
          DYNAMO_ENDPOINT: !If [IsLocalEnv, "", !Ref AWS::NoValue]
          STUB_AIS_TABLE_NAME: !Ref StubInterventionsTable
      Policies:
        - !Ref StubInterventionsTableReadPolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/ais-stub/ais-stub.ts
        Minify: true
        Sourcemap: true
        Target: es2022
        UseNpmCi: True

  AisStubInterventionsHandlerApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AisStubInterventionsHandler.Arn
      Principal: apigateway.amazonaws.com

  StubInterventionsTableReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAccessToStubInterventionsTable
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !GetAtt StubInterventionsTable.Arn


  OidcDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-OidcStore
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: grantId
          AttributeType: S
        - AttributeName: uid
          AttributeType: S
        - AttributeName: userCode
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI-1
          KeySchema:
            - AttributeName: grantId
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: GSI-2
          KeySchema:
            - AttributeName: uid
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: GSI-3
          KeySchema:
            - AttributeName: userCode
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  OidcStubSessionTableAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAccessToStubInterventionsTable
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:BatchWriteItem
            Resource:
              - !GetAtt OidcDynamoTable.Arn
              - !Sub "${OidcDynamoTable.Arn}/index/*"
                
  OidcApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-OidcApiGateway
      StageName: Live
      AlwaysDeploy: true

  OidcViewsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: oidc-nunjucks-views
      Description: Nunjucks templates for OIDC interaction views
      ContentUri: ./src/main/oidc-stub/views
      CompatibleRuntimes:
        - nodejs22.x

  OidcLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/oidc-stub/handler.ts
      Runtime: nodejs22.x
      Layers:
        - !Ref OidcViewsLayer
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          # These will always be over-written when running locally in parameters.json
          DYNAMO_ENDPOINT: !If [IsLocalEnv, "", !Ref AWS::NoValue]
          TABLE_NAME: !Ref OidcDynamoTable
          ISSUER_URL:  !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubIssuer ]
      Policies:
        - !Ref OidcStubSessionTableAccessPolicy
      Events:
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref OidcApiGateway
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            RestApiId: !Ref OidcApiGateway
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/oidc-stub/handler.ts
        Minify: true
        Sourcemap: true
        Target: es2022
        UseNpmCi: True
        Loader:
          - .node=file
  
  OidcStubCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:  
        !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubDomainName ]
      DomainValidationOptions:
        - DomainName: 
            !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubDomainName ]
          HostedZoneId: "{{resolve:ssm:/deploy/hosted-zone/oidc/hosted-zone-id}}"
      ValidationMethod: DNS

  OidcStubApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubDomainName ]
      SecurityPolicy: TLS_1_2
      RegionalCertificateArn: !Ref OidcStubCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL

  OidcStubApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubDomainName ]
      RestApiId: !Ref OidcApiGateway
      Stage: Live
    DependsOn:
      - OidcStubApiDomain

  OidcStubDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !FindInMap [ EnvironmentConfiguration, !Ref Environment, oidcStubDomainName ]
      HostedZoneId: "{{resolve:ssm:/deploy/hosted-zone/oidc/hosted-zone-id}}"
      AliasTarget:
        DNSName: !GetAtt OidcStubApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt OidcStubApiDomain.RegionalHostedZoneId