AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Authentication, IPV and SPOT stubs

#      Tags:
#        Service: Authentication, IPV and SPOT stubs
#        Source: govuk-one-login/orch-stubs
#        Owner: di-orchestration@digital.cabinet-office.gov.uk

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    AllowedValues:
      - dev
      - build
  CodeSigningConfigArn:
    Type: String
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: none
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [none, !Ref CodeSigningConfigArn]]
  UsePermissionsBoundary: !Not [!Equals [none, !Ref PermissionsBoundary]]
  IsNotProduction: !Not [!Equals [!Ref Environment, production]]
  IsLocalEnv: !Equals [!Ref Environment, local]
  IsDev: !Equals [!Ref Environment, dev]

Mappings:
  EnvironmentConfiguration:
    dev:
      authStubDomainName: authstub.oidc.authdev3.dev.account.gov.uk
      authDomain: authdev3.dev.account.gov.uk
      orchToAuthSigningPublicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHzG8IFx1jE1+Ul44jQk96efPknCXVxWS4PqLrKfR/31UQovFQLfyxA46uiMOvr7+0hRwFX1fQhagsIK+dfB5PA==
    build:
      authStubDomainName: authstub.oidc.build.account.gov.uk
      authDomain: build.account.gov.uk
      orchToAuthSigningPublicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENRdvNXHwk1TvrgFUsWXAE5oDTcPrCBp6HxbvYDLsqwNHiDFEzCwvbXKY2QQR/Rtel0o156CtU9k1lCZJGAsSIA==

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  AuthCodeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-AuthStub-AuthCode
      KeySchema:
        - AttributeName: authCode
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: authCode
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: authCode

  AccessTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-AuthStub-AccessToken
      KeySchema:
        - AttributeName: accessToken
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: accessToken
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: accessToken

  UserProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-AuthStub-UserProfile
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: subjectId
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: SubjectIdIndex
          KeySchema:
            - AttributeName: subjectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: userProfile

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ApiGateway
      StageName: Live
      AlwaysDeploy: true
      Tags:
        FMSRegionalPolicy: false
        CustomPolicy: true

  AuthAuthorizeLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/auth-stub/auth-authorize.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          ENCRYPTION_KEY_ID: !GetAtt AuthEncryptionKey.KeyId
          AUTH_AUTHORIZE_PUBLIC_ENCRYPTION_KEY: !GetAtt AuthEncryptionKey.KeyId
          ORCH_TO_AUTH_CLIENT_ID: "orchestrationAuth"
          ORCH_TO_AUTH_AUDIENCE: !Sub
            - "https://signin.${authDomain}/"
            - authDomain:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  authDomain,
                ]
          # These will always be over-written when running locally in parameters.json
          LOCALSTACK_ENDPOINT: !If [IsLocalEnv, "", !Ref AWS::NoValue]
          DUMMY_ENCRYPTION_PUBLIC_KEY: !If [IsLocalEnv, "", !Ref AWS::NoValue]
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /authorize
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /authorize
            Method: post
      Policies:
        - !Ref AuthCodeTableWriteAccessPolicy
        - !Ref UserProfileTableReadAccessPolicy
        - !Ref UserProfileTableWriteAccessPolicy
        - !Ref AuthEncryptionKeyAccessPolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/auth-stub/auth-authorize.ts
        Minify: true
        Sourcemap: true
        Target: node20
        UseNpmCi: True

  AuthTokenLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/auth-stub/auth-token.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          ORCH_TO_AUTH_TOKEN_SIGNING_PUBLIC_KEY:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              orchToAuthSigningPublicKey,
            ]
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /token
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /token
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/auth-stub/auth-token.ts
        Minify: true
        Sourcemap: true
        Target: node20
        UseNpmCi: True

  AuthUserInfoLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/auth-stub/auth-userinfo.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /userinfo
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /userinfo
            Method: post
      Policies:
        - !Ref AuthCodeTableWriteAccessPolicy
        - !Ref AccessTokenTableWriteAccessPolicy
        - !Ref UserProfileTableReadAccessPolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/auth-stub/auth-userinfo.ts
        Minify: true
        Sourcemap: true
        Target: node20
        UseNpmCi: True

  AuthCodeTableReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubAuthCodeTableReadAccess
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Get*
            Resource: !GetAtt AuthCodeTable.Arn

  AuthCodeTableWriteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubAuthCodeTableWriteAccess
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource: !GetAtt AuthCodeTable.Arn

  AccessTokenTableReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubAccessTokenTableReadAccess
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Get*
            Resource: !GetAtt AccessTokenTable.Arn

  AccessTokenTableWriteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubAccessTokenTableWriteAccess
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource: !GetAtt AccessTokenTable.Arn

  UserProfileTableReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubUserProfileTableReadAccess
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Get*
            Resource: !GetAtt UserProfileTable.Arn

  UserProfileTableWriteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAuthStubUserProfileTableWriteAccess
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource: !GetAtt UserProfileTable.Arn

  AuthEncryptionKeyAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowDecryptOfParameters
            Effect: Allow
            Action: kms:Decrypt
            Resource: !GetAtt AuthEncryptionKey.Arn

  AuthEncryptionKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${Environment}-auth-stub-authentication-encryption-key"
      TargetKeyId: !Ref AuthEncryptionKey
  AuthEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Auth Stub KMS encryption key for decrypting requests from Orchestration
      PendingWindowInDays: 30
      KeyUsage: ENCRYPT_DECRYPT
      KeySpec: RSA_2048

  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          authStubDomainName,
        ]

Outputs:
  AuthHostedZoneId:
    Value: !GetAtt PublicHostedZone.Id
    Export:
      Name: AuthHostedZoneId
  AuthApiGatewayId:
    Value: !Ref ApiGateway
    Export:
      Name: AuthApiGatewayId
