services:
  localstack:
    container_name: localstack
    image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs,dynamodb
      - DEFAULT_REGION="eu-west-2"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/init-infra.sh:/etc/localstack/init/ready.d/start-localstack.sh
