AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SIS stub

#      Tags:
#        Service: Authentication, IPV and SPOT stubs
#        Source: govuk-one-login/orch-stubs
#        Owner: di-orchestration@digital.cabinet-office.gov.uk

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    Default: none
  CodeSigningConfigArn:
    Type: String
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: none
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Default: none
  VpcStackName:
    Type: String
    Description: The name of the stack used to create the VPC

Conditions:
  UseCodeSigning: !Not [!Equals [none, !Ref CodeSigningConfigArn]]
  UsePermissionsBoundary: !Not [!Equals [none, !Ref PermissionsBoundary]]
  IsLocalEnv: !Equals [!Ref Environment, local]

Mappings:
  EnvironmentConfiguration:
    dev:
      sisStubDomainName: sisstub.oidc.dev.account.gov.uk
      orchJwksUrl: https://oidc.authdev3.dev.account.gov.uk/.well-known/sis-jwks.json
    build:
      sisStubDomainName: sisstub.oidc.build.account.gov.uk
      orchJwksUrl: https://oidc.build.account.gov.uk/.well-known/sis-jwks.json

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  SISUserIdentityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-SisStub-UserIdentity
      KeySchema:
        - AttributeName: UserIdentityId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: UserIdentityId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: UserIdentity


  SISUserIdentityTableReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowUserIdentityTableReadAccess
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Get*
            Resource: !GetAtt SISUserIdentityTable.Arn

  SISUserIdentityTableWriteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowUserIdentityTableWriteAccess
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt SISUserIdentityTable.Arn

  SISApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ApiGateway
      StageName: Live
      AlwaysDeploy: true
      Tags:
        FMSRegionalPolicy: false
        CustomPolicy: true

  SISAuthorizeLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/sis-stub/sis-authorize.handler
      LoggingConfig:
        LogGroup: !Ref SISAuthorizeLambdaLogGroup
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Timeout: 10
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref SISApiGateway
            Path: /authorize
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref SISApiGateway
            Path: /authorize
            Method: post
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          SIS_PRIVATE_ENCRYPTION_KEY: "{{resolve:secretsmanager:/orch-stubs/sis-private-encryption-key:SecretString}}"
          ORCH_SIS_JWKS_URL:
            !FindInMap [EnvironmentConfiguration, !Ref Environment, orchJwksUrl]
          DYNAMO_ENDPOINT: !If [IsLocalEnv, "", !Ref AWS::NoValue]
          DUMMY_JWKS: !If [IsLocalEnv, "", !Ref AWS::NoValue]
          IDENTITY_STUB: "SisStub"
      Policies:
        - !Ref SISUserIdentityTableReadAccessPolicy
        - !Ref SISUserIdentityTableWriteAccessPolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/sis-stub/sis-authorize.ts
        Minify: true
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        Target: es2022
        UseNpmCi: True

  SISAuthorizeLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/orch-stubs/lambda/${Environment}-sis-authorize-lambda
      RetentionInDays: 30

  SISUserIdentityLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/shared-identity/handler/user-identity.handler
      LoggingConfig:
        LogGroup: !Ref SISUserIdentityLambdaLogGroup
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          IDENTITY_STUB: "SisStub"
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref SISApiGateway
            Path: /user-identity
            Method: get
      Policies:
        - !Ref SISUserIdentityTableReadAccessPolicy
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/shared-identity/handler/user-identity.ts
        Minify: true
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        Target: es2022
        UseNpmCi: True

  SISUserIdentityLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/orch-stubs/lambda/${Environment}-sis-user-identity-lambda
      RetentionInDays: 30

  SISJwksLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/main/sis-stub/sis-jwks.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          SIS_AUTHORIZE_PUBLIC_ENCRYPTION_KEY: "{{resolve:ssm:/orch-stubs/sis-public-encryption-key}}"
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref SISApiGateway
            Path: /.well-known/jwks.json
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/main/sis-stub/sis-jwks.ts
        Minify: true
        Sourcemap: true
        Target: es2022
        UseNpmCi: True

  SISStubCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        !FindInMap [ EnvironmentConfiguration, !Ref Environment, sisStubDomainName ]
      DomainValidationOptions:
        - DomainName:
            !FindInMap [ EnvironmentConfiguration, !Ref Environment, sisStubDomainName ]
          HostedZoneId: "{{resolve:ssm:/deploy/hosted-zone/oidc/hosted-zone-id}}"
      ValidationMethod: DNS

  SISStubApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, sisStubDomainName ]
      SecurityPolicy: TLS_1_2
      RegionalCertificateArn: !Ref SISStubCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL

  SISStubApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, sisStubDomainName ]
      RestApiId: !Ref SISApiGateway
      Stage: Live
    DependsOn:
      - SISStubApiDomain

  SISStubDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !FindInMap [ EnvironmentConfiguration, !Ref Environment, sisStubDomainName ]
      HostedZoneId: "{{resolve:ssm:/deploy/hosted-zone/oidc/hosted-zone-id}}"
      AliasTarget:
        DNSName: !GetAtt SISStubApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt SISStubApiDomain.RegionalHostedZoneId

Outputs:
  SISApiGatewayId:
    Value: !Ref SISApiGateway
    Export:
      Name: SISApiGatewayId
