AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Linking the root domain to the sub domain account for orchestration stubs.
Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build

Mappings:
  EnvironmentConfiguration:
    dev:
      oidcHostedZoneId: Z092159727B0APSLCJ6S7
      ipvStubDomainName: ipvstub.oidc.authdev3.dev.account.gov.uk
      ipvStubResourceRecords:
        [
          ns-567.awsdns-06.net,
          ns-1756.awsdns-27.co.uk,
          ns-1518.awsdns-61.org,
          ns-226.awsdns-28.com,
        ]
    build:
      oidcHostedZoneId: Z062899930H8VN1UJ9CDX
      ipvStubDomainName: ipvstub.oidc.build.account.gov.uk
      ipvStubResourceRecords:
        [
          ns-811.awsdns-37.net,
          ns-1515.awsdns-61.org,
          ns-1563.awsdns-03.co.uk,
          ns-300.awsdns-37.com,
        ]

Resources:
  IpvStubNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: NS
      Name:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          ipvStubDomainName,
        ]
      HostedZoneId:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          oidcHostedZoneId,
        ]
      ResourceRecords:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          ipvStubResourceRecords,
        ]
      TTL: 172800
