name: Deploy stubs build and promote

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.ORCH_STUBS_SAM_APP_VALIDATE_ROLE_ARN }}
  deploy:
    uses: ./.github/workflows/deploy-stubs.yml
    needs: run-checks
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.ORCH_STUBS_GH_ACTIONS_ROLE_ARN }}
      ARTIFACT_BUCKET_NAME: ${{ secrets.ORCH_STUBS_ARTIFACT_BUCKET_NAME }}
      SIGNING_PROFILE_NAME: ${{ secrets.ORCH_STUBS_SIGNING_PROFILE_NAME }}
