name: Deploy Stubs

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    secrets:
      GH_ACTIONS_ROLE_ARN:
        required: true
      ARTIFACT_BUCKET_NAME:
        required: true
      SIGNING_PROFILE_NAME:
        required: true
      WORKING_DIRECTORY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@99214aa6889fcddfa57764031d71add364327e59 # v6.1.3
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Cache SAM
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .aws-sam/cache
          key: orch-sam

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@245bad4dc21702a5e665f1ca615108f6e70546d2 # v4.0.0
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ${{ secrets.WORKING_DIRECTORY }}
