name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  merge_group:

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
